// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnTIeAw4DHgwUd2UvTIY-Govj2JNdzg8',
    appId: '1:162753424182:web:ec79030bc52ca227f42197',
    messagingSenderId: '162753424182',
    projectId: 'messageme-317db',
    authDomain: 'messageme-317db.firebaseapp.com',
    storageBucket: 'messageme-317db.appspot.com',
    measurementId: 'G-13JJS1JH0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpvcXluod235MBMzfQBcvBel4V2HdmG8',
    appId: '1:162753424182:android:41a6dbeda5682563f42197',
    messagingSenderId: '162753424182',
    projectId: 'messageme-317db',
    storageBucket: 'messageme-317db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs5MzDctLK90PQ7QzJ-WJVxxvLyDPY67Y',
    appId: '1:162753424182:ios:f4ac62ca81b67599f42197',
    messagingSenderId: '162753424182',
    projectId: 'messageme-317db',
    storageBucket: 'messageme-317db.appspot.com',
    iosBundleId: 'com.example.messageme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs5MzDctLK90PQ7QzJ-WJVxxvLyDPY67Y',
    appId: '1:162753424182:ios:564251a9aa76ac56f42197',
    messagingSenderId: '162753424182',
    projectId: 'messageme-317db',
    storageBucket: 'messageme-317db.appspot.com',
    iosBundleId: 'com.example.messageme.RunnerTests',
  );
}
